"""ChatGPT-subscription backend via the official Codex CLI.

When MODEL_BACKEND=codex, replies are generated by invoking the Codex CLI's
non-interactive mode (``codex exec``) once per reply, with tools/sandbox disabled
and a customer-service instruction. Authentication is whatever ``codex login``
("Sign in with ChatGPT") set up — this module never touches tokens itself.

This uses the official Codex client and OpenAI's sanctioned ChatGPT-login-for-
Codex. Caveats (documented in the README): Codex is a coding agent, replies are
slower than an API call, ChatGPT-plan rate limits apply, and there are no
embeddings (the KB falls back to keyword search).
"""

from __future__ import annotations

import logging
import os
import shlex
import subprocess
import tempfile
from pathlib import Path

from services.openai_service import OpenAIServiceError

log = logging.getLogger("smartel.codex")

DEFAULT_TIMEOUT = 180  # seconds per reply

# Default flags: read-only sandbox, no approval prompts, allow running outside a
# git repo. Override entirely via CODEX_EXEC_ARGS for other Codex versions.
_DEFAULT_EXEC_FLAGS = ["--skip-git-repo-check", "--sandbox", "read-only",
                       "--ask-for-approval", "never"]

CODEX_INSTRUCTION = (
    "You are a customer-service assistant replying on behalf of a business on "
    "Telegram. Using the conversation below, write ONLY the single reply message "
    "to send to the customer's latest message. Do not include any preamble, "
    "reasoning, code, file edits, or tool output — output just the reply text."
)


def binary() -> str:
    """The Codex executable (override with CODEX_BIN, e.g. an absolute path)."""
    return (os.environ.get("CODEX_BIN") or "codex").strip()


def is_available() -> bool:
    import shutil
    b = binary()
    return shutil.which(b) is not None or Path(b).exists()


def is_logged_in() -> bool:
    """Best-effort check that `codex login` has been completed (auth file present).
    May return False even when logged in if Codex stores creds elsewhere."""
    home = Path(os.environ.get("CODEX_HOME") or (Path.home() / ".codex"))
    return (home / "auth.json").exists()


def login(device_auth: bool = False) -> bool:
    """Run the interactive `codex login` flow (inherits the terminal). Returns
    True if the command exited successfully."""
    cmd = [binary(), "login"] + (["--device-auth"] if device_auth else [])
    try:
        return subprocess.run(cmd).returncode == 0
    except FileNotFoundError:
        print("   ! Codex CLI not found — install it first.")
        return False
    except Exception as e:  # pragma: no cover
        log.warning("codex login failed: %s", type(e).__name__)
        return False


def _build_prompt(messages: list[dict]) -> str:
    system = ""
    turns: list[str] = []
    for m in messages:
        role, content = m.get("role"), (m.get("content") or "")
        if role == "system":
            system = content
        elif role == "user":
            turns.append(f"Customer: {content}")
        elif role == "assistant":
            turns.append(f"Assistant: {content}")
    parts = [CODEX_INSTRUCTION]
    if system:
        parts.append("\nBusiness assistant instructions:\n" + system)
    parts.append("\n--- Conversation ---")
    parts.extend(turns)
    parts.append("--- End conversation ---")
    parts.append("\nReply to the latest customer message now:")
    return "\n".join(parts)


def _exec_flags() -> list[str]:
    override = (os.environ.get("CODEX_EXEC_ARGS") or "").strip()
    return shlex.split(override) if override else list(_DEFAULT_EXEC_FLAGS)


def chat(messages: list[dict], *, model: str | None = None) -> str:
    """Generate a reply via `codex exec`. Raises OpenAIServiceError on failure
    (same type the pipeline already handles)."""
    if not is_available():
        raise OpenAIServiceError(
            "Codex CLI not found. Install it (npm i -g @openai/codex) and run "
            "`codex login`.", kind="unknown")

    prompt = _build_prompt(messages)
    model = (model or os.environ.get("CODEX_MODEL") or "").strip() or None
    timeout = _timeout()

    with tempfile.TemporaryDirectory(prefix="smartel_codex_") as workdir:
        out_path = Path(workdir) / "reply.txt"
        cmd = [binary(), "exec", "-C", workdir,
               "--output-last-message", str(out_path)]
        cmd += _exec_flags()
        if model:
            cmd += ["-m", model]
        cmd += ["-"]  # read the prompt from stdin (avoids arg-length/escaping issues)

        try:
            proc = subprocess.run(cmd, input=prompt, capture_output=True, text=True,
                                  timeout=timeout, cwd=workdir)
        except FileNotFoundError as e:
            raise OpenAIServiceError("Codex CLI not found.", kind="unknown", cause=e) from e
        except subprocess.TimeoutExpired as e:
            raise OpenAIServiceError("Codex timed out generating a reply.",
                                     kind="timeout", cause=e) from e

        reply = ""
        try:
            reply = out_path.read_text(encoding="utf-8").strip()
        except OSError:
            pass
        if not reply:
            reply = (proc.stdout or "").strip()

        if proc.returncode != 0 and not reply:
            err = (proc.stderr or proc.stdout or "").strip()
            log.error("codex exec failed (exit %s): %s", proc.returncode, err[:500])
            kind = "auth" if _looks_like_auth_error(err) else "unknown"
            owner_msg = ("Codex isn't logged in — run `codex login` (Sign in with ChatGPT)."
                         if kind == "auth" else
                         "Codex failed to generate a reply. See logs.")
            raise OpenAIServiceError(owner_msg, kind=kind)
        if not reply:
            raise OpenAIServiceError("Codex returned an empty reply.", kind="unknown")
        return reply


def _timeout() -> int:
    try:
        return int(os.environ.get("CODEX_EXEC_TIMEOUT") or DEFAULT_TIMEOUT)
    except ValueError:
        return DEFAULT_TIMEOUT


def _looks_like_auth_error(text: str) -> bool:
    t = (text or "").lower()
    return any(k in t for k in ("login", "log in", "sign in", "auth", "unauthorized",
                                "not authenticated", "401"))
