"""ChatGPT-subscription backend via the official Codex CLI.

When MODEL_BACKEND=codex, replies are generated by invoking the Codex CLI's
non-interactive mode (``codex exec``) once per reply, with tools/sandbox disabled
and a customer-service instruction. Authentication is whatever ``codex login``
("Sign in with ChatGPT") set up — this module never touches tokens itself.

This uses the official Codex client and OpenAI's sanctioned ChatGPT-login-for-
Codex. Caveats (documented in the README): Codex is a coding agent, replies are
slower than an API call, ChatGPT-plan rate limits apply, and there are no
embeddings (the KB falls back to keyword search).
"""

from __future__ import annotations

import logging
import os
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path

from services.openai_service import OpenAIServiceError

log = logging.getLogger("smartel.codex")

DEFAULT_TIMEOUT = 180  # seconds per reply

# Flags for `codex exec`. exec is already non-interactive (it never prompts for
# approval), so we only need: allow running outside a git repo + a read-only
# sandbox. If a Codex version rejects these, we retry with the minimal set, then
# surface guidance to set CODEX_EXEC_ARGS. Override entirely via CODEX_EXEC_ARGS.
_DEFAULT_EXEC_FLAGS = ["--skip-git-repo-check", "--sandbox", "read-only"]
_MINIMAL_EXEC_FLAGS = ["--skip-git-repo-check"]

CODEX_INSTRUCTION = (
    "You are a customer-service assistant replying on behalf of a business on "
    "Telegram. Using the conversation below, write ONLY the single reply message "
    "to send to the customer's latest message. Do not include any preamble, "
    "reasoning, code, file edits, or tool output — output just the reply text."
)


def binary() -> str:
    """The Codex executable (override with CODEX_BIN, e.g. an absolute path)."""
    return (os.environ.get("CODEX_BIN") or "codex").strip()


def is_available() -> bool:
    b = binary()
    return shutil.which(b) is not None or Path(b).exists()


def install() -> bool:
    """Install the Codex CLI via npm (preferred) or Homebrew. Returns True if
    `codex` is available afterward. Best-effort; prints progress and guidance."""
    if is_available():
        return True
    candidates: list[list[str]] = []
    if shutil.which("npm"):
        candidates.append(["npm", "install", "-g", "@openai/codex"])
    if shutil.which("brew"):
        candidates.append(["brew", "install", "--cask", "codex"])
    if not candidates:
        print("   ! Couldn't auto-install: neither `npm` nor `brew` is on PATH.")
        print("     Install Node.js or Homebrew, then run one of:")
        print("       npm install -g @openai/codex")
        print("       brew install --cask codex")
        return False
    for cmd in candidates:
        print(f"   → Installing Codex CLI: {' '.join(cmd)}")
        try:
            rc = subprocess.run(cmd).returncode
        except Exception as e:  # pragma: no cover
            log.warning("codex install via %s failed: %s", cmd[0], type(e).__name__)
            continue
        if rc == 0 and is_available():
            print("   ✓ Codex CLI installed.")
            return True
        print(f"   ! `{cmd[0]}` finished (exit {rc}) but `codex` isn't on PATH yet.")
    if not is_available():
        print("   ! `codex` still isn't on PATH — you may need to restart your shell")
        print("     (or add the npm global / Homebrew bin to PATH), then re-run the wizard.")
    return is_available()


def is_logged_in() -> bool:
    """Best-effort check that `codex login` has been completed (auth file present).
    May return False even when logged in if Codex stores creds elsewhere."""
    home = Path(os.environ.get("CODEX_HOME") or (Path.home() / ".codex"))
    return (home / "auth.json").exists()


def login(device_auth: bool = False) -> bool:
    """Run the interactive `codex login` flow (inherits the terminal). Returns
    True if the command exited successfully."""
    cmd = [binary(), "login"] + (["--device-auth"] if device_auth else [])
    try:
        return subprocess.run(cmd).returncode == 0
    except FileNotFoundError:
        print("   ! Codex CLI not found — install it first.")
        return False
    except Exception as e:  # pragma: no cover
        log.warning("codex login failed: %s", type(e).__name__)
        return False


def _build_prompt(messages: list[dict]) -> str:
    system = ""
    turns: list[str] = []
    for m in messages:
        role, content = m.get("role"), (m.get("content") or "")
        if role == "system":
            system = content
        elif role == "user":
            turns.append(f"Customer: {content}")
        elif role == "assistant":
            turns.append(f"Assistant: {content}")
    parts = [CODEX_INSTRUCTION]
    if system:
        parts.append("\nBusiness assistant instructions:\n" + system)
    parts.append("\n--- Conversation ---")
    parts.extend(turns)
    parts.append("--- End conversation ---")
    parts.append("\nReply to the latest customer message now:")
    return "\n".join(parts)


def _flag_sets() -> list[list[str]]:
    """Flag sets to try in order. A user-provided CODEX_EXEC_ARGS overrides
    everything (no fallback); otherwise try the default set, then a minimal set
    if the default is rejected as an unexpected argument."""
    override = (os.environ.get("CODEX_EXEC_ARGS") or "").strip()
    if override:
        return [shlex.split(override)]
    return [list(_DEFAULT_EXEC_FLAGS), list(_MINIMAL_EXEC_FLAGS)]


def chat(messages: list[dict], *, model: str | None = None) -> str:
    """Generate a reply via `codex exec`. Raises OpenAIServiceError on failure
    (same type the pipeline already handles)."""
    if not is_available():
        raise OpenAIServiceError(
            "Codex CLI not found. Install it (npm i -g @openai/codex) and run "
            "`codex login`.", kind="unknown")

    prompt = _build_prompt(messages)
    model = (model or os.environ.get("CODEX_MODEL") or "").strip() or None
    timeout = _timeout()

    flag_sets = _flag_sets()
    rc, reply, stderr = 1, "", ""
    for idx, flags in enumerate(flag_sets):
        rc, reply, stderr = _run_exec(prompt, model, flags, timeout)
        if reply:
            return reply
        # Self-heal across Codex versions: if a flag was rejected, retry simpler.
        if rc != 0 and _is_arg_error(stderr) and idx + 1 < len(flag_sets):
            log.warning("codex exec rejected flags (%s); retrying with a simpler set.",
                        " ".join(flags))
            continue
        break

    if rc != 0:
        log.error("codex exec failed (exit %s): %s", rc, (stderr or "").strip()[:500])
        if _is_arg_error(stderr):
            raise OpenAIServiceError(
                "Codex rejected the exec flags for your CLI version. Set CODEX_EXEC_ARGS "
                "in .env to flags your `codex exec` accepts (or leave it blank).",
                kind="bad_request")
        if _looks_like_auth_error(stderr):
            raise OpenAIServiceError(
                "Codex isn't logged in — run `codex login` (Sign in with ChatGPT).",
                kind="auth")
        raise OpenAIServiceError("Codex failed to generate a reply. See logs.", kind="unknown")
    raise OpenAIServiceError("Codex returned an empty reply.", kind="unknown")


def _run_exec(prompt: str, model: str | None, flags: list[str], timeout: int):
    """Run one `codex exec` attempt. Returns (returncode, reply_text, stderr)."""
    with tempfile.TemporaryDirectory(prefix="smartel_codex_") as workdir:
        out_path = Path(workdir) / "reply.txt"
        cmd = [binary(), "exec", "-C", workdir, "--output-last-message", str(out_path)]
        cmd += flags
        if model:
            cmd += ["-m", model]
        cmd += ["-"]  # read the prompt from stdin (avoids arg-length/escaping issues)
        try:
            proc = subprocess.run(cmd, input=prompt, capture_output=True, text=True,
                                  timeout=timeout, cwd=workdir)
        except FileNotFoundError as e:
            raise OpenAIServiceError("Codex CLI not found.", kind="unknown", cause=e) from e
        except subprocess.TimeoutExpired as e:
            raise OpenAIServiceError("Codex timed out generating a reply.",
                                     kind="timeout", cause=e) from e
        reply = ""
        try:
            reply = out_path.read_text(encoding="utf-8").strip()
        except OSError:
            pass
        if not reply and proc.returncode == 0:
            reply = (proc.stdout or "").strip()
        return proc.returncode, reply, (proc.stderr or "")


def _is_arg_error(text: str) -> bool:
    t = (text or "").lower()
    return "unexpected argument" in t or ("error:" in t and "usage:" in t)


def _timeout() -> int:
    try:
        return int(os.environ.get("CODEX_EXEC_TIMEOUT") or DEFAULT_TIMEOUT)
    except ValueError:
        return DEFAULT_TIMEOUT


def _looks_like_auth_error(text: str) -> bool:
    t = (text or "").lower()
    return any(k in t for k in ("login", "log in", "sign in", "auth", "unauthorized",
                                "not authenticated", "401"))
